version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '${GOAPP_DB_PORT-3306}:3306'
    volumes:
      - './docker/mysql/init:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: '${GOAPP_DB_USER-go-user}'
      MYSQL_PASSWORD: '${GOAPP_DB_PASS-go-pass}'
      MYSQL_DATABASE: '${GOAPP_DB_DATABASE-godb}'

  goapp:
    build: docker/goapp
    ports:
      - '8080'
    depends_on:
      - 'db'
    environment:
      DB_USER: '${GOAPP_DB_USER-go-user}'
      DB_PASS: '${GOAPP_DB_PASS-go-pass}'
      DB_HOST: 'db'
      DB_PORT: '${GOAPP_DB_PORT-3306}'
      DB_DATABASE: '${GOAPP_DB_DATABASE-godb}'

  nginx:
    image: nginx:1.17
    ports:
      - '80:80'
    volumes:
      - './docker/nginx/conf:/etc/nginx/conf.d'
    depends_on:
      - 'goapp'